source 'https://github.com/CocoaPods/Specs.git'

inhibit_all_warnings!

use_frameworks! :linkage => :dynamic

target 'Example' do
  project 'Example.xcodeproj'
  platform :ios, '15.0'

  pod 'WannaUI'
end

post_install do |pi|
  pi.pods_project.targets.each do |t|
    t.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end
